import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Blog",
	description: "Generated by create next app",
};

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<header className="fixed w-full p-4 shadow-2xl top-0 left-0 right-0">
				Admin\Dashboard Header
			</header>
			<main className="mt-16">{children}</main>
		</>
	);
}
